cdl/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin

import symposion.views


WIKI_SLUG = r"(([\w-]{2,})(/[\w-]{2,})*)"


urlpatterns = patterns(
    "",
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^admin/", include(admin.site.urls)),

    url(r"^robots\.txt$", TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
    url(r"^account/signup/$", symposion.views.SignupView.as_view(), name="account_signup"),
    url(r"^account/login/$", symposion.views.LoginView.as_view(), name="account_login"),
    url(r"^account/", include("account.urls")),

    url(r"^conference/", include("symposion.conference.urls")),

    url(r"^dashboard/", symposion.views.dashboard, name="dashboard"),
    # url(r"^intervenant/", include("cdl.speakers.urls")),
    url(r"^intervenant/", include("symposion.speakers.urls")),
    # url(r"^speaker/", include("cdl.speakers.urls")),
    url(r"^speaker/", include("symposion.speakers.urls")),
    url(r"^proposals/", include("symposion.proposals.urls")),
    url(r"^sponsors/", include("symposion.sponsorship.urls")),
    url(r"^partenariat/", include("symposion.sponsorship.urls")),
    url(r"^boxes/", include("symposion.boxes.urls")),

    # url(r"^teams/", include("cdl.teams.urls")),
    url(r"^teams/", include("symposion.teams.urls")),

    url(r"^reviews/", include("symposion.reviews.urls")),
    # url(r"^coverage/", include("cdl.coverage.urls")),
    url(r"^inscription/", include("symposion.registration.urls")),

    url(r"^schedule/", include("symposion.schedule.urls")),
    url(r"^programme/", include("symposion.schedule.urls")),
    url(r"^conference/", include("symposion.conference.urls")),
    url(r"^coverage/", include("symposion.coverage.urls")),
    # url(r"^badges/", include("cdl.badges.urls")),
    url(r"^markitup/", include("markitup.urls")),
    url(r"^schedule/xml$", "cdl.views.schedule_xml", name="schedule_xml"),

    url(r"^", include("symposion.cms.urls")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cdl/conference/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _

from symposion.conference.models import Conference


class ConferenceCategory(models.Model):
    """
    a category of the conference such as "DevOps", "IoT",
    "Free culture", will be used as a label.
    """

    conference = models.ForeignKey(Conference, verbose_name=_("conference"))

    name = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.CharField(max_length=680, blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _(u"Conference category")
        verbose_name_plural = _(u"Thématiques")

cdl/proposals/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from multiselectfield.db.fields import MultiSelectField

from symposion.proposals.models import ProposalBase
from cdl.conference.models import ConferenceCategory


class Proposal(ProposalBase):

    AUDIENCE_LEVEL_NOVICE = 1
    AUDIENCE_LEVEL_EXPERIENCED = 2
    AUDIENCE_LEVEL_INTERMEDIATE = 3

    AUDIENCE_LEVELS = [
        (AUDIENCE_LEVEL_NOVICE, _(u"Novice")),
        (AUDIENCE_LEVEL_INTERMEDIATE, _(u"Intermediate")),
        (AUDIENCE_LEVEL_EXPERIENCED, _(u"Experienced")),
    ]

    VIDEO_OUTPUT = (
        ("VGA", u"VGA"),
        ("DVI", u"DVI"),
        ("HDMI", u"HDMI"),
        ("DPORT", u"Display Port"),
        ("MDPORT", u" Mini Display Port"),
    )

    category = models.ForeignKey(ConferenceCategory)

    audience_level = models.IntegerField(
        _("Audience level"),
        choices=AUDIENCE_LEVELS)

    prerequistes = models.TextField(
        _("Prerequistes"),
        help_text=_("If Prerequistes are needed to follow this talk or workshop."),
        blank=True
    )

    video_output = MultiSelectField(
        _("Video output"),
        choices=VIDEO_OUTPUT,
        help_text=_("Specify video output."),
        blank=True,
    )

    broadcast_audio = models.BooleanField(
        _("Broadcast audio"),
        default=None,
        help_text=_(u"Do you need audio material to broadcast audio ?")
    )

    recording_release = models.BooleanField(
        _("Recording release"),
        default=True,
        help_text=_(u"By submitting your proposal, you agree to give permission to the conference organizers to record, edit, and release audio and/or video of your presentation. If you do not agree to this, please uncheck this box.")
    )

    def __unicode__(self):
        return u"#%s - %s (%s)" % (self.number, self.title, self.speaker)

    class Meta:
        abstract = True


class TalkProposal(Proposal):

    DURATION_CHOICES = [
        (0, _(u"No preference")),
        (1, _(u"I prefer a 20 minute slot")),
        (2, _(u"I prefer a 50 minute slot")),
    ]

    duration = models.IntegerField(_("Duration"), choices=DURATION_CHOICES)

    class Meta:
        verbose_name = _(u"talk proposal")


class TutorialProposal(Proposal):

    DURATION_CHOICES = [
        (0, _(u"No preference")),
        (1, _(u"I prefer a 1h20 slot")),
        (2, _(u"I prefer a 2h50 slot")),
    ]

    duration = models.IntegerField(_("Duration"), choices=DURATION_CHOICES)

    class Meta:
        verbose_name = _(u"tutorial proposal")


class StandProposal(ProposalBase):

    organisation = models.CharField(max_length=150)

    def __unicode__(self):
        return u"#%s - %s (%s)" % (self.number, self.title, self.speaker)

    class Meta:
        verbose_name = _(u"stand proposal")

cdl/proposals/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from markitup.widgets import MarkItUpWidget

from .models import TalkProposal, TutorialProposal, StandProposal


class ProposalForm(forms.ModelForm):

    def clean_description(self):
        value = self.cleaned_data["description"]
        if len(value) > 400:
            raise forms.ValidationError(
                _(u"The description must be less than 400 characters")
            )
        return value


class TalkProposalForm(ProposalForm):

    class Meta:
        model = TalkProposal
        fields = [
            "title",
            "category",
            "audience_level",
            "description",
            "abstract",
            "prerequistes",
            "duration",
            "additional_notes",
            "video_output",
            "broadcast_audio",
            "recording_release",
        ]
        widgets = {
            "abstract": MarkItUpWidget(),
            "additional_notes": MarkItUpWidget(),
        }


class TutorialProposalForm(ProposalForm):

    class Meta:
        model = TutorialProposal
        fields = [
            "title",
            "category",
            "audience_level",
            "description",
            "abstract",
            "prerequistes",
            "duration",
            "additional_notes",
            "video_output",
            "broadcast_audio",
            "recording_release",
        ]
        widgets = {
            "abstract": MarkItUpWidget(),
            "additional_notes": MarkItUpWidget(),
        }

class StandProposalForm(ProposalForm):

    class Meta:
        model = StandProposal
        fields = [
            "title",
            "organisation",
            "description",
            "abstract",
            "additional_notes",
        ]
        widgets = {
            "abstract": MarkItUpWidget(),
            "additional_notes": MarkItUpWidget(),
        }

cdl/views.py
import datetime

from django.http import HttpResponse
from django.utils.html import escape
from django.utils.text import slugify
from symposion.schedule.models import Room, Presentation


def schedule_xml(request):

    result = """<?xml version="1.0" encoding="UTF-8"?>
<schedule>
  <conference>
    <title>Capitole du Libre 2015</title>
    <subtitle/>
    <venue>ENSEEIHT (26 rue Riquet, Toulouse)</venue>
    <city>Toulouse</city>
    <start>2015-11-21</start>
    <end>2015-11-22</end>
    <days>2</days>
    <day_change>09:00:00</day_change>
    <timeslot_duration>00:05:00</timeslot_duration>
  </conference>
"""

    days = [datetime.date(2015, 11, 21), datetime.date(2015, 11, 22)]
    for index, day in enumerate(days):
        result += '  <day index="%s" date="%s">\n' % (index+1, day)
        for room in Room.objects.all():
            result += '    <room name="%s">\n' % room
            for p in Presentation.objects.filter(slot__day__date=day, slot__slotroom__room=room).distinct():
                start_at = datetime.datetime.combine(day, p.slot.start)
                end_at = datetime.datetime.combine(day, p.slot.end)
                duration = end_at - start_at
                result += """      <event id="%(id)s">
        <start>%(start)s</start>
        <duration>%(duration)s</duration>
        <room>%(room)s</room>
        <slug>%(slug)s</slug>
        <title>%(title)s</title>
        <subtitle/>
        <track>%(track)s</track>
        <type>%(type)s</type>
        <language/>
        <abstract>%(abstract)s</abstract>
        <description>%(description)s</description>
        <persons>
          <person id="%(person_id)s">%(person)s</person>
        </persons>
        <links>
        </links>
      </event>\n""" % {
                    'id': p.id,
                    'start': p.slot.start.strftime('%H:%M'),
                    'duration': '%02d:%02d' % (duration.total_seconds() / 3600, duration.total_seconds() % 3600 / 60),
                    'room': room,
                    'slug': slugify(p.title),
                    'title': escape(p.title),
                    'track': escape(p.proposal.category),
                    'type': p.proposal.kind,
                    'abstract': escape(p.description),
                    'description': escape(p.abstract),
                    'person_id': p.speaker.id,
                    'person': escape(p.speaker),
                }
            result += "    </room>\n"
        result += "  </day>\n"
    result += "</schedule>\n"
    return HttpResponse(result, content_type="application/xml")

cdl/templates/proposals/_categories_list.html
<div class="thematiques row">
{% for category in categories %}
<div class="col-xs-6 col-md-3">
  <div class="thumbnail">
    <h3>{{ category.name }}</h3>
    <p>{{ category.description }}</p>
    <p>
      <a href="{% url "schedule_list" "conferences" category.slug %}">Conférences</a>
        |
      <a href="{% url "schedule_list" "ateliers" category.slug %}">Ateliers</a>
    </p>
  </div>
</div><div class="{% cycle '' 'clearfix visible-xs' '' 'clearfix' %}"></div>
{% endfor %}
</div>

cdl/templates/proposals/_pending_proposal_row.html
{% load i18n %}

<tr>
    <td>
        <a href="{% url "proposal_detail" proposal.pk %}">{{ proposal.title }}</a>
    </td>

    <td>{{ proposal.kind.name }}</td>

    <td>
        {% if proposal.cancelled %}
            <span class="label label-important">{% trans 'Cancelled' %}</span>
        {% else %}
            {% if request.user == proposal.speaker.user %}
                {% if proposal.result.status == "accepted" %}
                    <span class="label label-success">{% trans "Accepted" %}</span>
                {% else %}
                    <span class="label label-default">{% trans "Submitted" %}</span>
                {% endif %}
            {% else %}
                <span class="label label-default">{% trans "Invited" %}</span>
            {% endif %}
        {% endif %}
    </td>

    <td>
        {% if not proposal.cancelled %}
            <div class="btn-group">
                <a class="btn btn-xs dropdown-toggle" data-toggle="dropdown" href="#">
                {% trans 'Choose Response' %}
                <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url "proposal_pending_join" proposal.id %}">
			{% trans 'Accept invitation' %}</a></li>
                    <li><a href="{% url "proposal_pending_decline" proposal.id
		    %}">{% trans 'Decline invitation' %}</a></li>
                </ul>
            </div>
        {% endif %}
    </td>
</tr>

cdl/templates/proposals/_proposal_categories.html
{% categories as categories %}

<div class="thematiques row">
{% for category in categories %}
  <div class="col-xs-6 col-sm-4 col-md-3">
    <div class="thumbnail">
      <h3>{{category.name}}</h3>
      <p>{{category.description}}</p>
    </div>
  </div>
{% endfor %}
</div>

cdl/templates/proposals/_proposal_fields.html
{% load i18n %}

<dl class="dl-horizontal">
    <dt>{% trans "Submitted by" %}</dt>
    <dd>{{ proposal.speaker }}</dd>

    <dt>{% trans "Track" %}</dt>
    <dd>{{ proposal.category }}&nbsp;</dd>

    <dt>{% trans "Audience Level" %}</dt>
    <dd>{{ proposal.get_audience_level_display }}&nbsp;</dd>

    <dt>{% trans "Duration" %}</dt>
    <dd>{{ proposal.get_duration_display }}&nbsp;</dd>

    {% if proposal.additional_speakers.all %}
        <dt>{% trans "Additional Speakers" %}</dt>
        <dd>
            {% for speaker in proposal.additional_speakers.all %}
                <li>
                    {% if speaker.user %}
                        <strong>{{ speaker.name }}</strong> &lt;{{ speaker.email }}&gt;
                    {% else %}
                        {{ speaker.email }} ({% trans "Invitation Sent" %})
                    {% endif %}
                </li>
            {% endfor %}
        </dd>
    {% endif %}

    <dt>{% trans "Description" %}</dt>
    <dd>{{ proposal.description }}&nbsp;</dd>

    <dt>{% trans "Abstract" %}</dt>
    <dd>{{ proposal.abstract|safe }}&nbsp;</dd>

    <dt>{% trans "Notes" %}</dt>
    <dd>{{ proposal.additional_notes|safe }}&nbsp;</dd>

    <dt>{% trans "Speaker Bio" %}</dt>
    <dd>{{ proposal.speaker.biography|safe }}&nbsp;</dd>

    <dt>{% trans "Documents" %}</dt>
    <dd>
        {% if proposal.supporting_documents.exists %}
            <table class="table table-striped">
                {% for document in proposal.supporting_documents.all %}
                    <tr>
                        <td><a href="{{ document.download_url }}">{{ document.description }}</a></td>
                        <td>
                        <form style="margin: 0;" method="post" action="{% url "proposal_document_delete" document.pk %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-xs">delete</button>
                        </form>
                    </td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            {% trans "No supporting documents attached to this proposal." %}
        {% endif %}
    </dd>
</dl>

cdl/templates/proposals/_proposal_row.html
{% load i18n %}

<tr>
    <td>
        <a href="{% url "proposal_detail" proposal.pk %}">{{ proposal.title }}</a>
    </td>

    <td>{{ proposal.kind.name }}</td>

    <td>
        {% if proposal.cancelled %}
            <span class="label label-danger">{% trans "Cancelled" %}</span>
        {% else %}
            {% if request.user == proposal.speaker.user %}
                {% if proposal.result.status == "accepted" %}
                    <span class="label label-success">{% trans 'Accepted' %}</span>
                {% else %}
                    <span class="label label-default">{% trans 'Submitted' %}</span>
                {% endif %}
            {% else %}
                <span class="label label-default">{% trans 'Associated' %}</span>
            {% endif %}
        {% endif %}
    </td>

    <td>
        {% if not proposal.cancelled %}
            {% if request.user == proposal.speaker.user and proposal.can_edit %}
                {% if proposal.presentation %}
                <a href="{% url "schedule_presentation_detail" proposal.presentation.pk %}" class="btn btn-sm btn-default" target="_blank">{% trans "Display" %}</a>
                {% endif %}
                <a href="{% url "proposal_edit" proposal.pk %}" class="btn btn-sm btn-default"><i class="icon-pencil"></i>{% trans "Edit" %}</a>
                <a href="{% url "proposal_speaker_manage" proposal.id %}" class="btn btn-sm btn-default"><i class="icon-user"></i>{% trans 'Manage Additional Speakers' %}</a>
            {% endif %}
        {% endif %}
    </td>
</tr>

cdl/templates/proposals/base.html
{% extends "site_base_onecolumn.html" %}

{% block body_outer %}
    {% block body %}{% endblock %}
{% endblock %}

cdl/templates/proposals/document_create.html
{% extends "proposals/base.html" %}

{% load bootstrap %}

{% block page_title %}Upload Document to '{{ proposal.title }}'{% endblock %}

{% block body %}
    <form method="POST" action="" enctype="multipart/form-data" class="form form-horizontal">
        {% csrf_token %}
        <fieldset>
            {{ form|bootstrap_horizontal }}
        </fieldset>
        <div class="form-actions">
            <input class="btn btn-primary" type="submit" value="Upload" />
        </div>
    </form>
{% endblock %}

cdl/templates/proposals/proposal_cancel.html
{% extends "proposals/base.html" %}

{% load i18n %}

{% block head_title %}{% trans 'Cancel Proposal' %}{% endblock %}

{% block body %}
    <h1>Cancel: {{ proposal.title }}</h1>

    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <p>{% trans "Are you sure you want to cancel <b>{{ proposal.title }}</b>?" %}</p>
        <input class="btn btn-danger" type="submit" value="I am sure" />
        <a class="btn btn-default" href="{% url "proposal_detail" proposal.pk %}">{% trans 'No, keep it for now' %}</a>
    </form>
{% endblock %}

cdl/templates/proposals/proposal_detail.html
{% extends "proposals/base.html" %}

{% load i18n %}
{% load account_tags %}
{% load bootstrap %}
{% load markitup_tags %}

{% block head_title %}{{ proposal.title }}{% endblock %}

{% block extra_head %}{% markitup_media %}{% endblock %}

{% block body %}
    <div class="pull-right">
        {% if not proposal.cancelled %}
            {% if request.user == proposal.speaker.user %}
                <a href="{% url "proposal_edit" proposal.pk %}" class="btn btn-default">
                    {% trans "Edit this proposal" %}
                </a>
                <a href="{% url "proposal_cancel" proposal.pk %}" class="btn btn-default">
                    {% trans "Cancel this proposal" %}
                </a>
            {% else %}
                <a href="{% url "proposal_leave" proposal.pk %}" class="btn btn-default">
                    {% trans "Remove me from this proposal" %}
                </a>
            {% endif %}
        {% else %}
            <span class="label label-danger">{% trans 'Cancelled' %}</span>
        {% endif %}
    </div>

    <h2>#{{ proposal.number }}: {{ proposal.title }} <br/><small>{{ proposal.kind }} {%trans 'by' %} <em>{{ proposal.speaker }}</em></small></h2>

    <div class="tabbable">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#proposal-detail" data-toggle="tab">{% trans "Proposal Details" %}</a></li>
            {% if request.user == proposal.speaker.user %}
                <li><a href="#proposal-documents" data-toggle="tab">{% trans "Supporting Documents" %}</a></li>
            {% endif %}
            {% if message_form %}
                <li><a href="#proposal-feedback" data-toggle="tab">{% trans "Reviewer Feedback" %} <span class="badge">{{ proposal.messages.all|length }}</span></a></li>
            {% endif %}
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="proposal-detail">
                {% include "proposals/_proposal_fields.html" %}
            </div>
            {% if request.user == proposal.speaker.user %}
                <div class="tab-pane" id="proposal-documents">
                    <h3>{% trans 'Supporting Documents' %}</h3>

                    {% if proposal.supporting_documents.exists %}
                        <table class="table table-striped">
                            {% for document in proposal.supporting_documents.all %}
                                <tr>
                                    <td><a href="{{ document.download_url }}">{{ document.description }}</a></td>
                                    <td>
                                    <form style="margin: 0;" method="post" action="{% url "proposal_document_delete" document.pk %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-xs">{% trans 'delete' %}</button>
                                    </form>
                                </td>
                                </tr>
                            {% endfor %}
                        </table>
                    {% else %}
                        <p>{% trans 'No supporting documents attached to this proposal.' %}</p>
                    {% endif %}
                    <a class="btn btn-sm{% if proposal.cancelled %} btn-disabled{% endif %}" href="{% url "proposal_document_create" proposal.pk %}"><i class="fa fa-upload"></i> {% trans 'Add Document' %}</a>
                </div>
            {% endif %}

    {% if message_form %}
        <div class="tab-pane" id="proposal-feedback">

            <h3>{% trans 'Conversation with Reviewers' %}</h3>

            {% for message in proposal.messages.all %}
                <div class="review-box">
                    <div class="comment">{{ message.message|safe }}</div>
                    <div class="dateline"><b>{% user_display message.user %}</b> {{ message.submitted_at|timesince }} ago</div>
                </div>
                <div class="clear"></div>
            {% endfor %}

            <h3>{% trans 'Leave a Message' %}</h3>

            <p>{% trans 'You can leave a message for the reviewers here.' %}</p>

            <form action="" method="POST" accept-charset="utf-8">
                {% csrf_token %}
                <fieldset>
                    {{ message_form|bootstrap }}
                </fieldset>
                <div class="actions">
                    <button type="submit" name="message_submit" class="btn btn-primary">{% trans 'Submit' %}</button>
                </div>
            </form>
        </div>
    {% endif %}
    </div>
</div>
{% endblock %}

{% block extra_script %}
    <script src="{{ STATIC_URL }}symposion/js/jquery.history.js"></script>
    <script type="text/javascript">
        $(function() {
            var History = window.History;

            $(window).bind("anchorchange", function() {
                $(".nav-tabs a[href='" + location.hash + "']").click();
            });

            $('#.nav-tabs a[data-toggle="tab"]').on('shown', function (e) {
                if (History.enabled) {
                    History.pushState(null, null, $(e.target).attr("href"));
                }
            });
        });
    </script>
{% endblock extra_script %}

cdl/templates/proposals/proposal_edit.html
{% extends "proposals/base.html" %}

{% load i18n %}
{% load bootstrap %}
{% load markitup_tags %}

{% block head_title %}Editing {{ proposal.title }}{% endblock %}

{% block extra_head %}{% markitup_media %}{% endblock %}

{% block body %}
    <h1>Edit: {{ proposal.title }}</h1>

    <p><a href="{% url "proposal_speaker_manage" proposal.pk %}">{% trans "Manage speakers" %}</a></p>

    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
            {{ form|bootstrap }}
        </fieldset>
        <div class="form-actions">
            <input class="btn btn-primary" type="submit" value="Save" />
            <a class="btn btn-default" href="{% url "proposal_detail" proposal.pk %}">{% trans "Cancel" %}</a>
        </div>
    </form>
{% endblock %}

cdl/templates/proposals/proposal_leave.html
{% extends "proposals/base.html" %}

{% block body %}
    <h3>Leaving {{ proposal.title }}</h3>

    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Are you sure you wish to leave as a speaker on <b>{{ proposal.title }}</b>?</p>
        <input type="submit" class="btn btn-primary" value="I am sure" />
    </form>
{% endblock %}

cdl/templates/proposals/proposal_speaker_manage.html
{% extends "proposals/base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block body %}
    <h2>{% trans 'Proposal:' %} {{ proposal.title }}</h2>
    
    <p>
      <a href="{% url "proposal_edit" proposal.pk %}">{% trans 'Edit proposal' %}
      </a>
    </p>

    <h2>{% trans 'Current Speakers' %}</h2>

    {% for speaker in speakers %}
        {% if speaker.user %}
            <p><b>{{ speaker.name }}</b> &mdash; {{ speaker.email }}</p>
        {% else %}
            <p>{{ speaker.email }} &mdash; {% trans 'pending invitation' %}</p>
        {% endif %}
    {% endfor %}

    <h2>{% trans 'Add another speaker' %}</h2>

    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ add_speaker_form|bootstrap }}
        <div class="form-action">
            <input type="submit" value="Add speaker" class="btn btn-primary" />
        </div>
    </form>
{% endblock %}

{% block extra_body %}
    <script type="text/javascript">
    $(function() {
        $("#id_email").focus();
    });
    </script>
{% endblock %}

cdl/templates/proposals/proposal_submit.html
{% extends "proposals/base.html" %}

{% load boxes_tags %}
{% load i18n %}

{% block page_title %}{% trans "Submit A Proposal" %}{% endblock %}

{% block body %}
    <h2>{% trans "Submit A Proposal" %}</h2>
    {% box "proposal_submit" %}

    {% if kinds %}
        <p>{%trans "Select what kind of proposal you'd like to submit:" %}</p>
    
        <ul>
            {% for kind in kinds %}
                <li><a href="{% url "proposal_submit_kind" kind.slug %}">{{ kind }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>{%trans "Proposals are not currently open for submission." %}</p>
    {% endif %}
{% endblock %}

cdl/templates/proposals/proposal_submit_kind.html
{% extends "proposals/base.html" %}

{% load bootstrap %}
{% load boxes_tags %}
{% load markitup_tags %}
{% load i18n %}

{% block page_title %}Submit a Proposal for a {{ kind.name }}{% endblock %}

{% block body %}
    <h2>{% blocktrans %}Submit a Proposal for a {{ kind.name }}{% endblocktrans %}</h2>
    {% box "example_proposal" %}

    <form method="POST" action="" enctype="multipart/form-data" class="form-horizontal">
        {% csrf_token %}
        <fieldset>
            {{ form|bootstrap_horizontal }}
        </fieldset>
        <div class="form-actions">
            <p>
                {%trans "You will be able to edit your proposal after it has been submitted. The program committee may ask questions, provide feedback, and even suggest changes to your proposal as part of the review processes." %}
            </p>
            <input class="btn btn-primary" type="submit" name="finish" value="{% trans "Save" %}" />
            <!-- <span style="float: right; padding: 4px 6px">or</span> -->
            <input class="btn btn-default" type="submit" name="add-speakers" value="{% trans "Save and Add Additional Speakers" %}" />
        </div>
    </form>
{% endblock %}